# Generated by Django 5.0 on 2023-12-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunitarios', '0002_remove_cliente_mismo_emial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
