# Generated by Django 5.0 on 2023-12-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunitarios', '0004_rename_nombres_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
